<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-10-11 10:28:52
 */
return [
    'allShared' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all-shared-de7b91ffb4a07857c568c9d1e7b36cfa.js',
        ],
        'css' => [
            'all-shared-f3693417f0142d18c1691bb04752b70e.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'allBackEnd' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all-backend-3017a116971229b8dc9b381e0f9a6fc7.js',
        ],
        'css' => [
            'all-backend-5b119a1d1127a7b341c02a5dbed9c56c.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'allFrontEnd' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'allShared',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'allShared',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'allShared',
        ],
    ],
    'rmrevin\\yii\\fontawesome\\AssetBundle' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'allShared',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'allBackEnd',
        ],
    ],
    'yii\\jui\\JuiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'allBackEnd',
        ],
    ],
    'app\\themes\\adminlte2\\AdminLteAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'rmrevin\\yii\\fontawesome\\AssetBundle',
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'allBackEnd',
        ],
    ],
    'app\\themes\\adminlte2\\ShowLoadingAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'allBackEnd',
        ],
    ],
    'app\\themes\\adminlte2\\AdminltePluginsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'app\\themes\\adminlte2\\AdminLteAsset',
            'app\\themes\\adminlte2\\ShowLoadingAsset',
            'allBackEnd',
        ],
    ],
    'app\\plugins\\menu\\assets\\MenuAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\jui\\JuiAsset',
            'allBackEnd',
        ],
    ],
    'app\\themes\\adminlte2\\ThemeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\themes\\adminlte2\\AdminltePluginsAsset',
            'allBackEnd',
        ],
    ],
    'nirvana\\showloading\\ShowLoadingAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'allBackEnd',
        ],
    ],
    'lo\\modules\\noty\\assets\\NotyAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'allBackEnd',
        ],
    ],
];